# netlify.toml

[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  
  # ✅ Google Sheets & API Configuration
  VITE_GOOGLE_SHEET_ID = "1tkYiGokyeJyBmPuf92-PBfwhCTjIAjMhv-bhXbXEVOo"
  VITE_GOOGLE_API_KEY = "AIzaSyDb5WAIaBhJNNkGeAHYzPG9345ImAWbZoE"
  VITE_GOOGLE_CLIENT_ID = "505713902225-qquc0qhnfg040o5fq6l30nkl5a3u4h44.apps.googleusercontent.com"
  VITE_GOOGLE_CALENDAR_ID = "7ff204be43d9977d20a0e71282ae335a973e6b2a812dad20a429b6d20fbf91aa@group.calendar.google.com"
  
  # ✅ Sheet Names
  VITE_INTERNSHIPS_SHEET_NAME = "Internships"
  VITE_EVENTS_SHEET_NAME = "Events"
  VITE_WEBINAR_SHEET_NAME = "Webinars"
  VITE_TEAM_SHEET_NAME = "Our Team"
  
  # ✅ Backend API
  VITE_API_URL = "https://main-webpage-l85m.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    # ✅ UPDATED CSP - Allow Google APIs
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://apis.google.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https: blob:; font-src 'self' data: https://fonts.gstatic.com; connect-src 'self' https://firebasestorage.googleapis.com https://identitytoolkit.googleapis.com https://securetoken.googleapis.com https://sheets.googleapis.com https://www.googleapis.com https://main-webpage-l85m.onrender.com;"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
