CREATE TABLE IF NOT EXISTS certificates (
  id VARCHAR(36) PRIMARY KEY,
  certificate_id VARCHAR(50) UNIQUE NOT NULL,
  internship_id VARCHAR(36),
  application_id VARCHAR(36),
  user_id VARCHAR(36),
  recipient_name VARCHAR(255) NOT NULL,
  recipient_email VARCHAR(255) NOT NULL,
  course_name VARCHAR(255) NOT NULL,
  duration VARCHAR(50) NOT NULL,
  completion_date DATE NOT NULL,
  issue_date DATE DEFAULT (CURRENT_DATE),
  grade VARCHAR(10),
  score DECIMAL(5,2),
  certificate_url VARCHAR(500),
  qr_code_url VARCHAR(500),
  verification_hash VARCHAR(64) UNIQUE,
  is_verified BOOLEAN DEFAULT true,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (internship_id) REFERENCES internships(id) ON DELETE SET NULL,
  FOREIGN KEY (application_id) REFERENCES internship_applications(id) ON DELETE SET NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_certificates_certificate_id (certificate_id),
  INDEX idx_certificates_verification_hash (verification_hash),
  INDEX idx_certificates_is_verified (is_verified)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
